// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Mirrors Next.js's own env precedence (.env.local overrides .env) so the
// Prisma CLI never silently falls back to a stale .env value when only
// .env.local was updated (e.g. after rotating the DB password) — plain
// `dotenv/config` only ever loads ".env" and has no idea .env.local exists.
loadEnv();
loadEnv({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Migrate/Studio need a direct (non-pooled) connection — the running app's
  // PrismaClient uses the pooled DATABASE_URL via its own adapter instead (see src/lib/db.ts).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
