// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Migrate/Studio need a direct (non-pooled) connection — the running app's
  // PrismaClient uses the pooled DATABASE_URL via its own adapter instead (see src/lib/db.ts).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
